config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  resources :binarytrees 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/binaryTreeClass.rb
class Node
   attr_accessor :data, :leftChild, :rightChild

   def initialize(data)
      @data = data
      @leftChild = nil
      @rightChild = nil
   end

   # def setData
   #    print "Data (enter an integer used as the data of the new node): "
   #    return gets.chomp
   #    # TODO:update, if data is not an integer, say invalid input and ask again for data
   # end

end

class BinaryTree

   attr_accessor :head, :result

   # Constructor called when object is created
   def initialize()
      @head = nil # head is a variable only visible in this class?? update check
      @result = ""
      @preorderTraversalResult = ""
      @inorderTraversalResult = ""
      @postorderTraversalResult = ""
   end

   def insert(data)
      # Insertion of first node
      newNode = Node.new(data)

      trvPtr = @head

      if @head == nil
         @head = newNode
      else # Insertion of additional nodes
         while trvPtr != nil
            trvPtrParent = trvPtr
            if newNode.data < trvPtr.data
               trvPtr = trvPtr.leftChild
               if trvPtr == nil
                  trvPtrParent.leftChild = newNode
               end #if
            else
               trvPtr = trvPtr.rightChild
               if trvPtr == nil
                  trvPtrParent.rightChild = newNode
               end #if
            end #if
         end #while
      end #if
      @result = data.to_s + " inserted!"
   end # def insert

   def search(startNode,parentOfStartNode,inData) # set @result
      trvPtr = startNode
      parentPtr = parentOfStartNode # used for node removal (see remove function)

      while (trvPtr != nil) && (inData != trvPtr.data)
         parentPtr = trvPtr
         if inData < trvPtr.data
            trvPtr = trvPtr.leftChild
         elsif inData > trvPtr.data
            trvPtr = trvPtr.rightChild
         end #if
      end #while

      if trvPtr == nil
         @result = inData.to_s + " not found."
         return nil, nil
         # need explicit return b/c of weird return valud of this string
         # undefined method `leftChild' for "4 not found.":String
      else
         @result = inData.to_s + " found!"
         return trvPtr, parentPtr

      end #if

   end # def search

   def remove(startNode,parentOfStartNode,data) #parentOfStartNode = nil if startNode is root
      nodeToRemove, parentOfNodeToRemove = search(startNode, parentOfStartNode,data)
      if nodeToRemove == nil
         @result = data.to_s + " not removed (not found in tree)"
         return nil
      #elsif nodeToRemove == @head

      elsif nodeToRemove.leftChild == nil && nodeToRemove.rightChild == nil
         # both children equal nil. easy. simply remove node
         if nodeToRemove == @head
            @head = nil # tree was just 1 node, now its 0 nodes
         elsif parentOfNodeToRemove.leftChild != nil &&
            parentOfNodeToRemove.leftChild.data == nodeToRemove.data
            # finds child of parent that should be deleted

            parentOfNodeToRemove.leftChild = nil
         else
            parentOfNodeToRemove.rightChild = nil
         end #if
      elsif nodeToRemove.leftChild == nil || nodeToRemove.rightChild == nil
         # one child equals nil. have parent point to child
         if nodeToRemove.leftChild == nil
            if nodeToRemove == @head
               @head = @head.rightChild
            elsif parentOfNodeToRemove.leftChild != nil &&
               parentOfNodeToRemove.leftChild.data == nodeToRemove.data
               # finds child of parent that should be deleted
               parentOfNodeToRemove.leftChild = nodeToRemove.rightChild
            else
               parentOfNodeToRemove.rightChild = nodeToRemove.rightChild
            end #if
         else # right child == nil
            if nodeToRemove == @head
               @head = @head.leftChild
            elsif parentOfNodeToRemove.leftChild != nil &&
               parentOfNodeToRemove.leftChild.data == nodeToRemove.data
               # finds child of parent that should be deleted
               parentOfNodeToRemove.leftChild = nodeToRemove.leftChild
            else
               parentOfNodeToRemove.rightChild = nodeToRemove.leftChild
            end #if
         end #if
      else # node-to-remove has 2 children
         # no special logic required for removing root in this case
         # find smallest value in right subtree
         trvPtr = nodeToRemove.rightChild
         minimumNode = nil
         while trvPtr != nil
            minimumNode = trvPtr
            trvPtr = trvPtr.leftChild
         end #while

         # replace value of node-to-remove with value of minimum
         nodeToRemove.data = minimumNode.data

         # remove minimum node from right subtree since it has been moved
         remove(nodeToRemove.rightChild,nodeToRemove,nodeToRemove.data)

      end #if
      @result = "Removed " + data.to_s + "!"
   end # def remove data

   def status
      return @result
   end

   def visitPreorder(node) # used in traversals
      @preorderTraversalResult = @preorderTraversalResult + " " + node.data.to_s
   end # def visit

   def visitInorder(node) # used in traversals
      @inorderTraversalResult = @inorderTraversalResult + " " + node.data.to_s
   end # def visit

   def visitPostorder(node) # used in traversals
      @postorderTraversalResult = @postorderTraversalResult + " " + node.data.to_s
   end # def visit

   def preOrderTraversal(node)
      if node == @head # reset result variable to print traversals
         @preorderTraversalResult = ""
      end #if
      if node != nil
         visitPreorder(node)
         preOrderTraversal(node.leftChild)
         preOrderTraversal(node.rightChild)
      end #if
      return @preorderTraversalResult
   end # def preOrderTraversal

   def inOrderTraversal(node)
      if node == @head # reset result variable to print traversals
         @inorderTraversalResult = ""
      end #if
      if node != nil
         inOrderTraversal(node.leftChild)
         visitInorder(node)
         inOrderTraversal(node.rightChild)
      end #if

      return @inorderTraversalResult
   end # def inOrderTraversal

   def postOrderTraversal(node)
      if node == @head # reset result variable to print traversals
         @postorderTraversalResult = ""
      end #if
      if node != nil
         postOrderTraversal(node.leftChild)
         postOrderTraversal(node.rightChild)
         visitPostorder(node)
      end #if

      return @postorderTraversalResult
   end # def postOrderTraversal



end #BinaryTree

$binaryTree = BinaryTree.new

app/controllers/binarytrees_controller.rb
require_relative  'binaryTreeClass' # this was needed b/c global $binaryTree was null
class BinarytreesController < ApplicationController
   def create
      t1 = Time.now.to_f
      if params[:commit] == 'Insert'
         #TODO: allow title param to be "00000n" where n is any # of random items to insert
         #if params[:binarytree][:title][0..4] == "00000"
         #inString = params[:binarytree][:title]
         #num = inString[5..inString.size-1].to_i
         #$binaryTree.insertMultipleRandom(num)
         $binaryTree.insert(params[:binarytree][:title].to_i) # to_i converts string to int
      elsif params[:commit] == 'Search'
         $binaryTree.search($binaryTree.head,nil,params[:binarytree][:title].to_i)
      elsif params[:commit] == 'Remove'
         # TODO: implement remove all
         # if params[:binarytree][:title] == "00000" # zeros b/c text cant be input
         #$binaryTree.removeAll()
         #else
         $binaryTree.remove($binaryTree.head,nil,params[:binarytree][:title].to_i)
         #end #if
      end
      t2 = Time.now.to_f
      time_ms = (t2-t1) * 1000
      $binaryTree.result = $binaryTree.result + " - " + (time_ms.round(2)).to_s + "ms"
      redirect_to home_index_url
   end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/binarytrees_helper.rb
module BinarytreesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/> <!-- For bootstrap -->
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css"> <!-- For Lobster font -->
<style>
.input {
   padding: 10px;
}
.center {
   text-align: center;
}

.title {
   font-family: Lobster, Monospace;
}

body {
   background-color:  #e0e0d1;
}

.width {
   width: 100px !important;
}


</style>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<!--
<form>
   <div class="row input center">
      <input type="text" placeholder="ex) 56">
   </div>
   <div class="row">
      <div class="col-xs-4">
      </div>
      <div class="col-xs-6">
         <button class="btn btn-success width">Insert</button>
         <button class="btn btn-primary width">Search</button>
         <button class="btn btn-danger width">Remove</button>
      </div>
      <div class="col-xs-5">
      </div>
   </div>


</form>
-->
<body>

   <!-- GitHub-corners logo link in top right corner -->
   <a href="https://github.com/AndrewERAU/rubyBinaryTree" class="github-corner" aria-label="View source on Github"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#ec1622; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>


   <div class="container">
<h1 class="center title">Welcome to the Ruby Binary Tree</h1>
<%= form_for :binarytree, url: binarytrees_path do |f| %>
  <p class="input center">
    <%= f.text_field :title,type: "number", placeholder: "72"%>
  </p>
  <p style="text-align:center;">
    <%= f.submit "Insert", class: "btn btn-success width"%>
    <%= f.submit "Search", class: "btn btn-primary width"%>
    <%= f.submit "Remove", class: "btn btn-danger width"%>
  </p>
  <p style="text-align:center; padding: 20px;">
     <!-- prints status without dereferencing null object -->
     <%= f.label (($binaryTree && $binaryTree.status) || "") %>
  </p>
  <p style="text-align:center; padding: 5px;">
     <!-- prints traversal without dereferencing null object -->
     <%= f.label "Preorder: " + (($binaryTree && $binaryTree.preOrderTraversal($binaryTree.head)) || "") %>
  </p>
  <p style="text-align:center;">
     <!-- prints traversal without dereferencing null object -->
     <%= f.label "Inorder: " + (($binaryTree && $binaryTree.inOrderTraversal($binaryTree.head)) || "") %>
  </p>
  <p style="text-align:center;">
     <!-- prints traversal without dereferencing null object -->
     <%= f.label "Postorder: " + (($binaryTree && $binaryTree.postOrderTraversal($binaryTree.head)) || "") %>
  </p>
  </div>
</body>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyBinaryTree</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>